import sqlite3
from pathlib import Path
from rl_swapper import config

def get_connection(db_path: Path = config.load_settings().db_file_path) -> sqlite3.Connection:
    """Get a connection to the swaps database and ensure the schema exists."""
    conn = sqlite3.connect(db_path, detect_types=sqlite3.PARSE_DECLTYPES)
    # allow concurrent reads/writes and reduces locking issues
    conn.execute("PRAGMA journal_mode=WAL;")
    # enable foreign key constraints
    conn.execute("PRAGMA foreign_keys=ON;")
    # allow accessing columns by name
    conn.row_factory = sqlite3.Row
    
    # create tables if they don't exist
    _ensure_schema(conn)
    
    return conn

def _ensure_schema(conn: sqlite3.Connection) -> None:
    """Create the swaps table if it doesn't exist."""
    conn.execute(
        # id: UUID string generated by the app on SwapRecord creation
        # with_thumbnails: boolean stored as integer
        # status: prepared, pushed, reverted, deleted
        # created_at, pushed_at: iso string
        """
        CREATE TABLE IF NOT EXISTS swaps (
            id TEXT PRIMARY KEY,
            installation_key TEXT NOT NULL CHECK(installation_key IN ('EpicGames', 'Steam')),
            target_name TEXT NOT NULL,
            donor_name TEXT NOT NULL,
            target_id INTEGER NOT NULL,
            donor_id INTEGER NOT NULL,
            target_product TEXT,
            donor_product TEXT,
            target_quality TEXT,
            donor_quality TEXT,
            target_slot TEXT,
            donor_slot TEXT,
            target_unlock_method TEXT,
            donor_unlock_method TEXT,
            target_asset_package TEXT,
            donor_asset_package TEXT,
            target_asset_path TEXT,
            donor_asset_path TEXT,
            with_thumbnails INTEGER NOT NULL DEFAULT 0,
            target_thumb_name TEXT,
            donor_thumb_name TEXT,
            status TEXT NOT NULL CHECK(status IN ('prepared', 'pushed', 'reverted', 'deleted')),
            created_at TEXT NOT NULL,
            pushed_at TEXT
        );
    """)
    conn.commit()